package figurasx;
/**
 *
 * @author david
 */
public class SampleFormFiguras extends javax.swing.JFrame {
    
    private PlCirculo objCirculo = new PlCirculo();
    private PlCuadrado objCuadrado = new PlCuadrado();
    private PlRectangulo objRectangulo = new PlRectangulo();
    private PlTrianguloR objTrianguloR = new PlTrianguloR();
    private PlRombo objRombo = new PlRombo();
    private PlTrapecio objTrapecio = new PlTrapecio();
    
    private void inicializarFiguras() {
	JCirculo.setContentPane(objCirculo);
	objCirculo.setSize(300,300);
	JCirculo.setSize(300,330);

	JCuadrado.setContentPane(objCuadrado);
	objCuadrado.setSize(300,300);
	JCuadrado.setSize(300,330);

	JRectangulo.setContentPane(objRectangulo);
	objRectangulo.setSize(300,300);
	JRectangulo.setSize(300,330);

	JTrianguloR.setContentPane(objTrianguloR);
	objTrianguloR.setSize(300,300);
	JTrianguloR.setSize(300,330);

	JRombo.setContentPane(objRombo);
	objRombo.setSize(300,300);
	JRombo.setSize(300,330);

	JTrapecio.setContentPane(objTrapecio);
	objTrapecio.setSize(300,300);
	JTrapecio.setSize(300,330);

        public SampleFormFiguras() {
            initComponents();
            this.inicializarFiguras();
}

    /**
     * Creates new form SampleFormFiguras
     */
            
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCirculo = new javax.swing.JInternalFrame();
        JCuadrado = new javax.swing.JInternalFrame();
        JRectangulo = new javax.swing.JInternalFrame();
        JTrianguloR = new javax.swing.JInternalFrame();
        JRombo = new javax.swing.JInternalFrame();
        JTrapecio = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiCirculo = new javax.swing.JMenuItem();
        jmiCuadrado = new javax.swing.JMenuItem();
        jmiRectangulo = new javax.swing.JMenuItem();
        jmiTrianguloR = new javax.swing.JMenuItem();
        jmiRombo = new javax.swing.JMenuItem();
        jmiTrapecio = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JCirculo.setClosable(true);
        JCirculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JCirculo.setVisible(false);

        javax.swing.GroupLayout JCirculoLayout = new javax.swing.GroupLayout(JCirculo.getContentPane());
        JCirculo.getContentPane().setLayout(JCirculoLayout);
        JCirculoLayout.setHorizontalGroup(
            JCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JCirculoLayout.setVerticalGroup(
            JCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JCuadrado.setClosable(true);
        JCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JCuadrado.setVisible(false);

        javax.swing.GroupLayout JCuadradoLayout = new javax.swing.GroupLayout(JCuadrado.getContentPane());
        JCuadrado.getContentPane().setLayout(JCuadradoLayout);
        JCuadradoLayout.setHorizontalGroup(
            JCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JCuadradoLayout.setVerticalGroup(
            JCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JRectangulo.setClosable(true);
        JRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JRectangulo.setVisible(false);

        javax.swing.GroupLayout JRectanguloLayout = new javax.swing.GroupLayout(JRectangulo.getContentPane());
        JRectangulo.getContentPane().setLayout(JRectanguloLayout);
        JRectanguloLayout.setHorizontalGroup(
            JRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JRectanguloLayout.setVerticalGroup(
            JRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JTrianguloR.setClosable(true);
        JTrianguloR.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JTrianguloR.setVisible(false);

        javax.swing.GroupLayout JTrianguloRLayout = new javax.swing.GroupLayout(JTrianguloR.getContentPane());
        JTrianguloR.getContentPane().setLayout(JTrianguloRLayout);
        JTrianguloRLayout.setHorizontalGroup(
            JTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JTrianguloRLayout.setVerticalGroup(
            JTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JRombo.setClosable(true);
        JRombo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JRombo.setVisible(false);

        javax.swing.GroupLayout JRomboLayout = new javax.swing.GroupLayout(JRombo.getContentPane());
        JRombo.getContentPane().setLayout(JRomboLayout);
        JRomboLayout.setHorizontalGroup(
            JRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JRomboLayout.setVerticalGroup(
            JRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JTrapecio.setClosable(true);
        JTrapecio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JTrapecio.setVisible(false);

        javax.swing.GroupLayout JTrapecioLayout = new javax.swing.GroupLayout(JTrapecio.getContentPane());
        JTrapecio.getContentPane().setLayout(JTrapecioLayout);
        JTrapecioLayout.setHorizontalGroup(
            JTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JTrapecioLayout.setVerticalGroup(
            JTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Figuras");

        jmiCirculo.setMnemonic('o');
        jmiCirculo.setText("Circulo");
        jmiCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCirculoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCirculo);

        jmiCuadrado.setMnemonic('s');
        jmiCuadrado.setText("Cuadrado");
        jmiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCuadradoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCuadrado);

        jmiRectangulo.setMnemonic('a');
        jmiRectangulo.setText("Rectangulo");
        jmiRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiRectangulo);

        jmiTrianguloR.setText("Triangulo Rectangulo");
        jmiTrianguloR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTrianguloRActionPerformed(evt);
            }
        });
        fileMenu.add(jmiTrianguloR);

        jmiRombo.setText("Rombo");
        jmiRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRomboActionPerformed(evt);
            }
        });
        fileMenu.add(jmiRombo);

        jmiTrapecio.setText("Trapecio");
        jmiTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTrapecioActionPerformed(evt);
            }
        });
        fileMenu.add(jmiTrapecio);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTrianguloR, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(689, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JRombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JTrianguloR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCirculoActionPerformed
        // TODO add your handling code here:
        JCirculo.setVisible(true);
    }//GEN-LAST:event_jmiCirculoActionPerformed

    private void jmiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCuadradoActionPerformed
        // TODO add your handling code here:
        JCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiCuadradoActionPerformed

    private void jmiRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRectanguloActionPerformed
        // TODO add your handling code here:
        JRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiRectanguloActionPerformed

    private void jmiTrianguloRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTrianguloRActionPerformed
        // TODO add your handling code here:
        JTrianguloR.setVisible(true);
    }//GEN-LAST:event_jmiTrianguloRActionPerformed

    private void jmiRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRomboActionPerformed
        // TODO add your handling code here:
        JRombo.setVisible(true);
    }//GEN-LAST:event_jmiRomboActionPerformed

    private void jmiTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTrapecioActionPerformed
        // TODO add your handling code here:
        JTrapecio.setVisible(true);
    }//GEN-LAST:event_jmiTrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SampleFormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SampleFormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SampleFormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SampleFormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SampleFormFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame JCirculo;
    private javax.swing.JInternalFrame JCuadrado;
    private javax.swing.JInternalFrame JRectangulo;
    private javax.swing.JInternalFrame JRombo;
    private javax.swing.JInternalFrame JTrapecio;
    private javax.swing.JInternalFrame JTrianguloR;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jmiCirculo;
    private javax.swing.JMenuItem jmiCuadrado;
    private javax.swing.JMenuItem jmiRectangulo;
    private javax.swing.JMenuItem jmiRombo;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiTrapecio;
    private javax.swing.JMenuItem jmiTrianguloR;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
